<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <Company>KakaoQuickLogin contributors</Company>
    <Copyright>Copyright © 2026</Copyright>
    <RepositoryType>git</RepositoryType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
